logging:
  file:
    name: src/main/resources/wildlife_tours.log

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/
    username: user
    password: password
    driverClassName:
  mvc:
    pathMatch:
      matching-strategy: ant-path-matcher