logging:
  file:
    name: src/main/resources/wildlife_tours.log

spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: mysql
#    url: jdbc:mysql://localhost:3306/mysql
    url: jdbc:mysql://us-cdbr-east-05.cleardb.net/heroku_d9dba035561c63c?password=edda012d&reconnect=true&user=be605943a5cabd
#    username: root
#    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    pathMatch:
      matching-strategy: ant-path-matcher
#  security:
#    user:
#      name: user
#      password: password12345678