logging:
  file:
    name: src/main/resources/wildlife_tours.log

spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: root
    driverClassName:
  mvc:
    pathMatch:
      matching-strategy: ant-path-matcher
  security:
    user:
      password: password12345678